language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

install:
  - "go version"
  - "go env"
  - "go get github.com/GeertJohan/go.rice/rice"
  - "go get -t -v ./..."

script:
  - "go generate"
  - "go test -race -coverprofile=coverage.txt -covermode=atomic -v"
  - "go build"

after_success:
  - "bash <(curl -s https://codecov.io/bash)"
