language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

install:
  - "go version"
  - "go env"
  - "go get github.com/GeertJohan/go.rice/rice"
  - "go get -t -v ./..."

script:
  - "go generate"
  - "go test -v"
  - "go build"
